### PR TITLE
Prevented deletion of User when deleting a Blog

### PR DESCRIPTION
**Pull request by laurensmartina**

### CODE REVIEW

**Comment by jan-vince** [comment]
Hi @laurensmartina ,

I will look at this and let you know!


Thanks for the PR,

Jan

**Comment by laurensmartina** [comment]
Hi @jan-vince , did you have a chance to look at this yet?

**Comment by jan-vince** [comment]
Hi @laurensmartina,

why have you changed relationship to hasOne?

From my point of view, blog User `hasMany` blog Posts. 

Blog Post `belongsTo` one blog User.

What is your use case you are trying to solve?

**Comment by laurensmartina** [comment]
Hi @jan-vince,
The problem was that when a BlogPost was deleted, so was the user, the ` 'delete' => 'false'` did not prevent this.
I modified the relationship like in the pull request and everything works as I expect it to work.

**Comment by jan-vince** [comment]
Hi @laurensmartina,

I have found the problem.

It was not in wrong definition of relationship but in forced model deletion on line [697 in Plugin.php](https://github.com/jan-vince/smallextensions/commit/7d69a2a668a15c1330611c06dcf0f908a9828ba5#diff-d213d482564b6755dded1b9c4a996b13L697).

There is an updated version of Small Extensions in October Marketplace.

Please test it and let me know.

**Comment by laurensmartina** [comment]
Thank you @jan-vince for fixing the problem.
I've tested it and it works correctly now. :-)

**Pull request closed without merging**
